name: Deploy Liquibase Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to VM and run Liquibase
      uses: google-github-actions/ssh-compute@v1
      with:
        instance_name: liquibase-vm
        zone: us-central1-a
        project_id: hd-liquibase-v2
        user: root
        ssh_private_key: ${{ secrets.VM_SSH_KEY }}
        command: |
          mkdir -p /opt/liquibase-project
          rm -rf /opt/liquibase-project/db
          cp -r $GITHUB_WORKSPACE/db /opt/liquibase-project/db
          cd /opt/liquibase-project
          liquibase \
            --url="jdbc:postgresql://10.0.0.3:5432/stage_db" \
            --username=liquibase_user \
            --password=${{ secrets.DB_PASSWORD }} \
            --changelog-file=db/changelog-master.xml \
            update

